version: '3.0'
services:

  postgres:
    image: postgres:12.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: kutaraev/food_backend:latest
    restart: always
    volumes:
      - static_data:/code/static/
      - media_data:/code/media/
    depends_on:
      - postgres
    env_file:
      - ./.env

  frontend:
    image: kutaraev/food_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs:/usr/share/nginx/html/api/docs/
      - static_data:/var/html/static/
      - media_data:/var/html/media/
    restart: always
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
  static_data:
  media_data:
